### ISSUE TITLE
ImportError: no module named 'calender'

### ISSUE THREAD

**Issue by xiaomingtt** [dotnfc/EPD_mpy_efont_demo#1]
ESP32S3N8R8，固件：ESP32_GENERIC_S3-SPIRAM_OCT-20240222-v1.22.2
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "ex10d2/app.py", line 7, in <module>
  File "/ex10d2/ui_calendar.py", line 7, in <module>
ImportError: no module named 'calender'

**Comment by dotnfc** [comment]
你需要使用 https://github.com/dotnfc/EPD_mpy_efont 中的定制固件。
如果只需要看看效果，可以在 windows 上双击运行 [efore-demo.cmd](https://github.com/dotnfc/EPD_mpy_efont_demo/blob/main/tools/win-cygwin/efore-demo.cmd) 即可。
